on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

name: "Build and Release Flutter App"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'  # Use Java 17
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Git tag
        run: git tag v0.0.${{ github.run_number }}  # Create a tag based on the run number
      - name: Push tag to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} v0.0.${{ github.run_number }}  # Push the tag with authentication
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: "build/app/outputs/apk/debug/*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
