on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

name: "Build and Release Flutter App"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2  # Updated to v2 for Java 17 support
        with:
          java-version: '17'  # Use Java 17
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --split-per-abi
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: "build/app/outputs/apk/debug/*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
